"""
Backup router: manual backup, list, download, restore, delete, schedule management.
"""
import uuid
from typing import Any

from fastapi import APIRouter, Depends, File, HTTPException, UploadFile
from fastapi.responses import FileResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.dependencies import get_current_user, require_superadmin
from app.database import get_db
from app.services import backup_service

router = APIRouter(prefix="/backup", tags=["backup"])


# ── List backups ──────────────────────────────────────────────────────────────

@router.get("/records")
async def list_backups(
    db: AsyncSession = Depends(get_db),
    _: Any = Depends(require_superadmin),
) -> list[dict]:
    records = await backup_service.list_backups(db)
    return [
        {
            "id": str(r.id),
            "filename": r.filename,
            "display_name": r.display_name,
            "file_size": r.file_size,
            "backup_type": r.backup_type,
            "status": r.status,
            "notes": r.notes,
            "created_at": r.created_at.isoformat(),
            "file_exists": getattr(r, "_file_exists", False),
        }
        for r in records
    ]


# ── Create manual backup ──────────────────────────────────────────────────────

@router.post("/create")
async def create_backup(
    notes: str | None = None,
    db: AsyncSession = Depends(get_db),
    _: Any = Depends(require_superadmin),
) -> dict:
    record = await backup_service.create_backup(db, backup_type="manual", notes=notes)
    return {
        "id": str(record.id),
        "filename": record.filename,
        "display_name": record.display_name,
        "file_size": record.file_size,
        "backup_type": record.backup_type,
        "status": record.status,
        "notes": record.notes,
        "created_at": record.created_at.isoformat(),
        "file_exists": True,
    }


# ── Upload external backup ────────────────────────────────────────────────────

@router.post("/upload")
async def upload_backup(
    file: UploadFile = File(...),
    db: AsyncSession = Depends(get_db),
    _: Any = Depends(require_superadmin),
) -> dict:
    """
    Accept an external .sql file, validate its structure, and store it.
    The stored record can then be restored via the normal restore endpoint.
    """
    _UPLOAD_LIMIT = 500 * 1024 * 1024  # 500 MB

    content = await file.read(_UPLOAD_LIMIT + 1)
    if len(content) > _UPLOAD_LIMIT:
        raise HTTPException(status_code=413, detail="Dosya 500 MB sınırını aşıyor.")

    result = backup_service.validate_sql_backup(content)
    if not result["valid"]:
        raise HTTPException(status_code=422, detail=result["error"])

    record = await backup_service.save_uploaded_backup(
        db, content, file.filename or "backup.sql"
    )
    await db.commit()

    return {
        "id": str(record.id),
        "filename": record.filename,
        "display_name": record.display_name,
        "file_size": record.file_size,
        "backup_type": record.backup_type,
        "status": record.status,
        "notes": record.notes,
        "created_at": record.created_at.isoformat(),
        "file_exists": True,
    }


# ── Download backup file ──────────────────────────────────────────────────────

@router.get("/{backup_id}/download")
async def download_backup(
    backup_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    _: Any = Depends(require_superadmin),
):
    fp, record = await backup_service.get_backup_file(db, backup_id)
    # ASCII-safe filename (no path traversal possible — record.filename is generated by us)
    return FileResponse(
        path=fp,
        filename=record.filename,
        media_type="application/octet-stream",
    )


# ── Restore from backup ───────────────────────────────────────────────────────

@router.post("/{backup_id}/restore")
async def restore_backup(
    backup_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    _: Any = Depends(require_superadmin),
) -> dict:
    return await backup_service.restore_backup(db, backup_id)


# ── Delete backup ─────────────────────────────────────────────────────────────

@router.delete("/{backup_id}")
async def delete_backup(
    backup_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    _: Any = Depends(require_superadmin),
) -> dict:
    await backup_service.delete_backup(db, backup_id)
    return {"message": "Yedek başarıyla silindi."}


# ── Schedule: get / save ──────────────────────────────────────────────────────

@router.get("/schedule")
async def get_schedule(
    db: AsyncSession = Depends(get_db),
    _: Any = Depends(require_superadmin),
) -> dict:
    return await backup_service.get_schedule(db)


@router.put("/schedule")
async def save_schedule(
    data: dict,
    db: AsyncSession = Depends(get_db),
    _: Any = Depends(require_superadmin),
) -> dict:
    return await backup_service.save_schedule(db, data)


# ── Next scheduled run info ───────────────────────────────────────────────────

@router.get("/next-run")
async def get_next_run(
    db: AsyncSession = Depends(get_db),
    _: Any = Depends(require_superadmin),
) -> dict:
    return await backup_service.get_next_run_info(db)


@router.get("/check-log")
async def get_check_log(
    db: AsyncSession = Depends(get_db),
    _: Any = Depends(require_superadmin),
) -> list:
    return await backup_service.get_check_log(db)
